torchbox/wagtailmedia

wagtailmedia/forms.py
The thumbnail is optional so let the user clear it
Fixes https://github.com/torchbox/wagtailmedia/issues/17
=> allow thumbnail to be cleared

.github/ISSUE_TEMPLATE.md
This feels like it would be useful on any Wagtail-related project that has a non-trivial API like this, and support for a wide range of versions. I'll merge this right away but feel free to make follow-up PRs with any relevant changes. In particular it might be good to use separate templates for bugs, support, and feature requests.
=> Add issue template from Wagtail

README.md
Fixes #54. This moves the docs around a bit, and adds a note about potential name clashes with Wagtail.
=> Document media field name clash. Fix #54

CHANGELOG.md, wagtailmedia/__init__.py
- Update edit handler `AdminMediaChooser` API to be compatible with Wagtail 2.0 and above ([#34](https://github.com/torchbox/wagtailmedia/issues/34), [#40](https://github.com/torchbox/wagtailmedia/pull/40)). Thanks to [@pahacofome](https://github.com/pahacofome)
`BaseMediaChooserPanel` is deprecated, and will be removed in a future release. Please use `AdminMediaChooser` instead ([#40](https://github.com/torchbox/wagtailmedia/pull/40)):
```diff
- from wagtailmedia.edit_handlers import BaseMediaChooserPanel
+ from wagtailmedia.edit_handlers import MediaChooserPanel
content_panels = Page.content_panels + [
-    BaseMediaChooserPanel('video_media'),
+    MediaChooserPanel('video_media'),
```
=> Release v0.3.1

.travis.yml, runtests.py, tox.ini, wagtailmedia/templates/wagtailmedia/chooser/results.html, wagtailmedia/utils.py, wagtailmedia/views/chooser.py, wagtailmedia/views/media.py
This Pull Request is a start to fix issue #62 
Right now, it's a test case that throws an error if the `RemovedInWagtail27Warning` warning occurs when the test suite is run. I'm not sure if there's a better way to handle that test, but I know this works.
Since there are two places in the code that calls the pagination utility (`views/chooser.py` and `views/media.py`), I am considering creating a `utils.py` with an implementation of the Django Paginator.
=> Wagtail 2.7 compatibility – Removing dependency on deprecated `wagtail.utils.pagination`

wagtailmedia/models.py, wagtailmedia/tests/test_models.py
'application/octet-stream' is the equivalent of None for mimetypes in
the correct type (string)
Fixes #76
=> simplify type checking for easy templating - None isn't useful here

README.md, wagtailmedia/tests/test_views.py, wagtailmedia/views/chooser.py
It just implements the same hook as `wagtail.documents` with its tests and documentation.
=> Allow hooks to modify chooser queryset

wagtailmedia/models.py
Had to fix import of `python_2_unicode_compatible` since it is removed from Django 3.
<https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis>
=> Fix Django 3 compability issue

.coveragerc, .travis.yml, README.md, codecov.yml, tox.ini
Following the setup for:
- https://github.com/wagtail/wagtail
- https://github.com/torchbox/wagtail-storages
With the difference that this uses the bash uploader ([recommended by codecov](https://github.com/codecov/example-python#whats-the-different-between-the-codecov-bash-and-codecov-python-uploader)), and uses the GitHub Marketplace app for codecov.
=> Set up code coverage collection and reporting with codecov

wagtailmedia/tests/testapp/models.py
This looks like a copy-paste issue when creating the project. It doesn’t seem like there would have been any consequences to this with the unit tests (it’s just the panel that was wrong), but for the new demo setup from #82 is impossible to use as-is.
=> Fix interactive demo and tests using the DocumentChooserPanel instead of MediaChooserPanel

CHANGELOG.md, wagtailmedia/tests/test_views.py, wagtailmedia/views/chooser.py
I fixed the problem that users those who don't have permission can see the media files.
=> securityfix: Filter media files by user permission in chooser panel

.travis.yml
Changes the Travis configuration so more work happens in parallel, and there is less time wasted installing all dependencies with pip / tox installs are cached.
=> CI improvements to speed up builds

wagtailmedia/tests/testapp/migrations/0001_initial.py
Discussed on Slack – this causes a migration to show whenever running the demo site, and seems to only be a remnant of Python 2 support.
There shouldn’t be any adverse consequences of updating the existing migration directly – so I’m tempted to merge this without further review, but I’ll leave it open for a few days in case others disagree.
=> Remove "b" bytes literal marker from initial migration of test app

.travis.yml, tox.ini, wagtailmedia/forms.py, wagtailmedia/models.py, wagtailmedia/permissions.py, wagtailmedia/tests/test_form_override.py, wagtailmedia/views/media.py
isort 5 was released on July 4, 2020, and introduces several breaking changes that prevent tests from succeeding on this repo. See https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/ for details.
=> Fixes to support isort version 5

wagtailmedia/blocks.py, wagtailmedia/tests/test_blocks.py
The expected behavior when using a custom AbstractMediaChooserBlock without a render_basic is to raise NotImplementedError, but instead you get this error:
`TypeError: render_basic() got an unexpected keyword argument 'context'`
This is because of an outdated signature which [changed in Wagtail 1.6](https://docs.wagtail.io/en/stable/releases/1.6.html#render-and-render-basic-methods-on-streamfield-blocks-now-accept-a-context-keyword-argument).
See Issue #19 and PR #20, which fixed the example in the README but didn't fix the intended functionality.
=> Fix expected NotImplementedError in Wagtail 1.6+

CHANGELOG.md, wagtailmedia/__init__.py
- Added filtering of media files by user permission in chooser panel ([#25](https://github.com/torchbox/wagtailmedia/pull/25)). Thanks to [@snj](https://github.com/snj)
- Added French translations ([#61](https://github.com/torchbox/wagtailmedia/pull/61)). Thanks to [@jeromelebleu](https://github.com/jeromelebleu).
- Add `{% block action %}` template block to allow overriding of form action in `add.html` template ([#102](https://github.com/torchbox/wagtailmedia/pull/102)). Thanks to [@thenewguy](https://github.com/thenewguy)
- Fix expected NotImplementedError in Wagtail 1.6+ ([#104](https://github.com/torchbox/wagtailmedia/pull/104)). Thanks to [@chosak](https://github.com/chosak) and [@Scotchester](https://github.com/Scotchester).
- Add support for uploading media files via the media …
=> Release v0.6.0

.travis.yml, manage.py, runtests.py, setup.py, tox.ini, wagtailmedia/forms.py, wagtailmedia/models.py, wagtailmedia/tests/settings.py, wagtailmedia/views/media.py, wagtailmedia/wagtail_hooks.py, wagtailmedia/widgets.py
Fixes #94
* Drops Django 1.11
* Set minimum Wagtail version to 2.7 (current LTS)
* Adds Python 3.8 and Django 3.0 to tox environments
=> Fix Django3 deprecation warnings

.travis.yml, setup.py, tox.ini, vagrant/README, vagrant/provision.sh
Lots of changes to the package’s peer dependencies:
- Removing Python 3.5
- Adding Python 3.9
- Remove Wagtail 2.8 and 2.9
- Adding Wagtail 2.11
- Adding Django 3.1
All of these are just package metadata & testing matrix changes.
=> Update supported & tested Python, Django, Wagtail versions

wagtailmedia/wagtail_hooks.py
Fixes #50
Note, did not add a test for this as Wagtail images/docs summary panels don't have them either
=> Only show MediaSummaryItem for users that can add/manage Media

wagtailmedia/templates/wagtailmedia/chooser/chooser.html
In wagtail 2.13, the `data-tab-nav` attribute is used for selecting tab nav elements, replacing selection by the `tab-nav` class (see https://github.com/wagtail/wagtail/commit/ca0154543aa79b463acf4a58ab45ccd8b8f6bd49). This adds the `data-tab-nav` attribute to the chooser.html template, fixing #129
=> Add data-tab-nav attribute to tab nav container

wagtailmedia/apps.py
Hello, I added `default_auto_field` to apps.py.
Django 3.2 now displays warning if `default_auto_field` is not defined in apps.py or settings.py.
Tested with Django 3.2.5 and 3.0.6
=> Fix default_auto_field not defined warning

README.md, src/wagtailmedia/admin.py, src/wagtailmedia/deprecation.py, src/wagtailmedia/forms.py, src/wagtailmedia/models.py, src/wagtailmedia/settings.py, tests/test_form_override.py, tests/test_models.py, tests/test_settings.py, tests/test_views.py
This PR fixes #112:
* adds thumnail extension validation (gif, png, jpg/jpeg, webp)
* moves settings to single namespaced setting (`WAGTAILMEDIA`)
* makes the audio/video extensions configurable, as well as provides (hpoefully) sensible defaults.
=> File extension validation

.github/workflows/test.yml, tox.ini
adds Python 3.10 in the mix, as well as Wagtail 2.15 (we already test against main)
=> Tidy up tox targets

src/wagtailmedia/forms.py, tests/test_form_override.py, tests/testapp/forms.py, tox.ini
This caused import issues for projects that subclassed ``BaseMediaForm``.
Updated tests to rely on overriding settings instead of mocking the return value.
Fixed tox config for dj32, which was accidentally only testing Django 3.1.x (the bug was introduced in 5e2f95eb6a).
Fixes #147
=> Removed module level call to ``get_media_base_form()``

tests/testapp/models.py
use_json_field is required with Wagtail >= 4.0
=> [Wagtail mainline] Conditionally use use_json_field in test app StreamField definition

tests/test_edit_handlers.py, tests/test_permissions.py, tests/test_views.py
Fix various test failures on current Wagtail main that are not really breakages, just changes to the HTML returned by Wagtail following the 4.0 redesign.
There are quite a few `RemovedInWagtail50Warning`s being thrown now, but they can probably wait for another time (especially as we might have dropped compatibility with some older versions by the time that comes round, which has a bearing on how we approach them.)
=> Update tests to match Wagtail 4.0 markup

src/wagtailmedia/templates/wagtailmedia/chooser/chooser.html, src/wagtailmedia/widgets.py
[MediaChooserPanel tabs not populating #166](https://github.com/torchbox/wagtailmedia/issues/166)
When using a remote static files storage the additional latency causes the inclusion of the [`static/wagtailmedia/js/tabs.js`](https://github.com/torchbox/wagtailmedia/blob/main/src/wagtailmedia/static/wagtailmedia/js/tabs.js) script within [`templates/wagtailmedia/chooser/chooser.html`](https://github.com/torchbox/wagtailmedia/blob/main/src/wagtailmedia/templates/wagtailmedia/chooser/chooser.html) to be deferred after [`static/wagtailmedia/js/media-chooser-modal.js`](https://github.com/torchbox/wagtailmedia/blob/main/src/wagtailmedia/static/wagtailmedia/js/media-chooser-modal.js) attempts to execute methods of the aforementioned script. This causes a `Uncaught ReferenceError` and prevents …
=> Fix dependancy resolution for `MediaChooserPanel` scripts

README.md
In some cases, the user will want to use or specify the video height, rather than use a hard-coded value. This example shows how to use the actual width and height values from the media item.
=> Pass video width and height to player

src/wagtailmedia/models.py
This PR was made to satisfy this issue: https://github.com/torchbox/wagtailmedia/issues/203
Simple PR that changes the `SearchField`s that have `partial_match=True` to use `AutocompleteField` and remove `partial_match`, which is bringing in a `RemovedInWagtail60Warning` when upgrading to `wagtail` 5.0.
Note: This is my first pull request/edit on an open-source repo. Sorry if I've missed anything or done something wrong - I'm open to learning! 😄
=> Changed `SearchField` with `partial_match` to `AutocompleteField`

.github/workflows/nightly-tests.yml, .github/workflows/test.yml, tests/test_blocks.py
* update Postgres to v15
* replace `assertQuerysetEqual` with `assertQuerySetEqual`
=> Fix nightly test for Wagtail 6.3 / Django 5.1

.github/workflows/test.yml, README.md, pyproject.toml, tox.ini
This PR updates the tox test setup to confirm package is compatible with Wagtail 6.3
Additionally:
- Python 3.8 is dropped due to deprecation and minimum Python version required is updated to 3.9
- Wagtail versions 6.0 and 6.1 are removed from tox tests due to deprecation.
- Django 5.1 and Python 3.13 are added to tox tests as compatible with Wagtail 6.3.
=> Update Tox for Wagtail 6.3

tests/test_api.py, tests/test_models.py, tests/test_views.py
In Wagtail 6.4 (https://github.com/wagtail/wagtail/pull/12787), updating the search index and reference index after a database update are now handled as background tasks through the django-tasks library. In the default configuration, this happens at the end of the current transaction (if any), and since unit tests are typically wrapped in a transaction, we can no longer count on the results of database updates within tests being immediately visible in search and object usage queries. To ensure that these tasks are executed, we trigger the oncommit hooks via `self.captureOnCommitCallbacks(execute=True)`.
=> Fix tests for background task behaviour in Wagtail 6.4

.github/workflows/test.yml, CHANGELOG.md, src/wagtailmedia/widgets.py, tests/test_api.py, tests/test_blocks.py, tests/test_models.py, tests/test_views.py, tox.ini
The changes primarily focus on updating the supported versions of  Wagtail.
- [tox.ini](https://github.com/torchbox/wagtailmedia/pull/262/commits/0b0d7a804512fb8ff0f6cd38ee823cb90c2924b8):
- Added testing for Wagtail 7.1 to the matrices
- [src/wagtailmedia/widgets.py](https://github.com/torchbox/wagtailmedia/pull/262/commits/8441c379b7aec4486aba70353df2235921bf2c09)
- Added variable import based upon version to handle moving of telepath in Wagtail 7.1
- [CHANGELOG.md](https://github.com/torchbox/wagtailmedia/pull/262/commits/39200596093bea1edaed88d4d0c3f9cf08de486c): Added an entry for the unreleased changes.
- Fix tests failing due to change in error message (https://github.com/torchbox/wagtailmedia/pull/262/commits/5463147edaed983935f5aa3a6bef0afcc9b5fc4c)
- Fix test that used removed …
=> Update to support Wagtail 7.1
