.drone.yml
setup.cfg
setup.py
wagtailmedia/__init__.py
wagtailmedia/admin.py
wagtailmedia/admin_urls.py
wagtailmedia/forms.py
wagtailmedia/models.py
wagtailmedia/permissions.py
wagtailmedia/templates/wagtailmedia/chooser/chooser.html
wagtailmedia/templates/wagtailmedia/media/add.html
wagtailmedia/templates/wagtailmedia/media/confirm_delete.html
wagtailmedia/templates/wagtailmedia/media/edit.html
wagtailmedia/templates/wagtailmedia/media/index.html
wagtailmedia/tests/settings.py
wagtailmedia/tests/test_permissions.py
wagtailmedia/tests/test_views.py
wagtailmedia/tests/testapp/models.py
wagtailmedia/tests/urls.py
wagtailmedia/views/chooser.py
wagtailmedia/views/media.py
wagtailmedia/wagtail_hooks.py

Make compatible with wagtail >=1.5 by converting AbstractMedia.search_fields to list.
If multiple-compatibility is needed I guess we could add some if-then logic.

Make compatible with Wagtail 1.5 +

---

README.md
setup.cfg
setup.py
wagtailmedia/migrations/0001_initial.py
wagtailmedia/models.py
wagtailmedia/views/media.py

Also fixed in #9, but I didn't spot that when making these changes. Apologies @MechanisM

8 taggable

---

wagtailmedia/blocks.py
wagtailmedia/edit_handlers.py
wagtailmedia/forms.py
wagtailmedia/migrations/0001_initial.py
wagtailmedia/models.py
wagtailmedia/permissions.py
wagtailmedia/templates/wagtailmedia/media/confirm_delete.html
wagtailmedia/templates/wagtailmedia/media/edit.html
wagtailmedia/tests/settings.py
wagtailmedia/tests/test_permissions.py
wagtailmedia/tests/test_views.py
wagtailmedia/tests/testapp/migrations/0001_initial.py
wagtailmedia/tests/testapp/models.py
wagtailmedia/tests/urls.py
wagtailmedia/views/chooser.py
wagtailmedia/views/media.py
wagtailmedia/wagtail_hooks.py
wagtailmedia/widgets.py

There are still 2 test failures that I believe has something to do with the way WAGTAIL_USAGE_COUNT_ENABLED was changed in Wagtail 2.0. Otherwise, all tests pass.

Support Wagtail 2.0 and Django 2.0

---

CHANGELOG.md
wagtailmedia/edit_handlers.py

from https://github.com/wagtail/wagtail/issues/4377#issuecomment-387565438

upgrade edit_handlers API to 2.0

---

tox.ini
wagtailmedia/templates/wagtailmedia/media/add.html
wagtailmedia/templates/wagtailmedia/media/edit.html
wagtailmedia/templates/wagtailmedia/media/index.html
wagtailmedia/tests/test_views.py
wagtailmedia/tests/testextends/templates/wagtailmedia/media/edit.html
wagtailmedia/tests/testextends/templates/wagtailmedia/media/index.html

More template blocks

---

README.md
wagtailmedia/forms.py
wagtailmedia/tests/test_form_override.py
wagtailmedia/tests/testapp/forms.py

Introduce setting for swappable media form

---

README.md

Provided by shields.io. https://img.shields.io/pypi/dm/wagtailmedia.svg

Add PyPI downloads badge to README

---

wagtailmedia/templates/wagtailmedia/media/add.html
wagtailmedia/tests/templates/wagtailmedia/media/add.html
wagtailmedia/tests/test_views.py

Fix issue 101

---

wagtailmedia/models.py

Drop python 2 unicode shim

---

wagtailmedia/edit_handlers.py

Remove deprecated BaseMediaChooserPanel

---

wagtailmedia/admin_urls.py
wagtailmedia/models.py
wagtailmedia/tests/urls.py
wagtailmedia/views/media.py
wagtailmedia/wagtail_hooks.py

117 - deprecations cleanup

---

wagtailmedia/templates/wagtailmedia/chooser/chooser.html
wagtailmedia/templates/wagtailmedia/media/add.html
wagtailmedia/templates/wagtailmedia/media/edit.html
wagtailmedia/tests/test_views.py
wagtailmedia/tests/testapp/migrations/0001_initial.py
wagtailmedia/tests/testapp/models.py

Add form media to add/edit/chooser templates

---

wagtailmedia/templates/wagtailmedia/chooser/chooser.html
wagtailmedia/tests/test_views.py
wagtailmedia/tests/testapp/apps.py
wagtailmedia/views/chooser.py

- ~[ ] fix for Wagtail 2.13 (issue #131)~ covered in #136

Update the media chooser

---

.pre-commit-config.yaml
src/wagtailmedia/edit_handlers.py
tests/test_edit_handlers.py

See [Upgrade considerations in release notes](https://docs.wagtail.org/en/latest/releases/3.0.html#api-changes-to-panels-edithandlers)
To run tests locally against main: `tox -e wagtailmain`

Fixes for wagtail 3.x

---

src/wagtailmedia/static/wagtailmedia/js/media-chooser.js

This fixes the issue mentioned in https://github.com/torchbox/wagtailmedia/issues/167#issuecomment-1230343828

Show edit button when item is chosen, refs #167

---

MANIFEST.in
src/wagtailmedia/models.py
src/wagtailmedia/templates/wagtailmedia/media/confirm_delete.html
src/wagtailmedia/templates/wagtailmedia/media/edit.html
src/wagtailmedia/templates/wagtailmedia/media/legacy/usage.html
src/wagtailmedia/templates/wagtailmedia/media/usage.html
src/wagtailmedia/views/media.py
tests/test_views.py
tests/testapp/models.py
tox.ini

Fix Wagtail 4.1 compatibility (usage counts)

---

README.md
src/wagtailmedia/api/serializers.py
src/wagtailmedia/api/views.py
tests/test_api.py
tests/urls.py
tests/utils.py

Add API viewset and serializer

---

.coveragerc
src/wagtailmedia/apps.py
src/wagtailmedia/blocks.py
src/wagtailmedia/edit_handlers.py
src/wagtailmedia/models.py
src/wagtailmedia/static/wagtailmedia/css/wagtailmedia-comparison.css
src/wagtailmedia/static/wagtailmedia/css/wagtailmedia.css
src/wagtailmedia/templates/wagtailmedia/widgets/compare.html
src/wagtailmedia/utils.py
src/wagtailmedia/wagtail_hooks.py
tests/test_blocks.py
tests/test_compare.py
tests/test_edit_handlers.py
tests/test_models.py
tests/test_utils.py
tests/utils.py

Does what is says on the tin 🥫
<details>
<summary>Screnshot 📸</summary>
</details>

Add field and block comparison

---

.github/workflows/publish.yml
.github/workflows/test.yml
.pre-commit-config.yaml
README.md
pyproject.toml
src/wagtailmedia/deprecation.py
tox.ini

- use PyPI trusted publishing
- update linter versions
- update tox to use wheels in testenv ([ref](https://hynek.me/articles/turbo-charge-tox/))
- tidy up readme (closes #210)

PyPI trusted publishing and tooling tweaks

---

src/wagtailmedia/static/wagtailmedia/css/wagtailmedia.css

This PR fixes the clean up static files issue.
The change was to remove the residue from static files (CSS/JS).
Fixes #219

fix: Fixed Clean up static files

---

.github/workflows/test.yml
pyproject.toml
tox.ini

Add Wagtail 5.2/ Python 3.12

---

tests/testapp/migrations/0001_initial.py

Ref: https://github.com/wagtail/wagtail/pull/11555

Fix collections import for latest Wagtail main
